/**
 * Disposable / temporary email blocklist.
 *
 * Used on both client and server to reject signups, contact requests,
 * and orders coming from throwaway inbox providers (10minutemail, tempmail, etc.).
 * List is intentionally exhaustive of the most common providers and their
 * many rotating aliases so the extensions/apps that generate them fail.
 */

const DISPOSABLE_DOMAINS = new Set<string>([
  // 10minutemail family
  "10minutemail.com", "10minutemail.net", "10minutemail.org", "10minutemail.co.uk",
  "10minutemail.de", "10minutemail.info", "10minutemail.us", "10minemail.com",
  "10minutmail.pl", "10minut.com.pl", "10mail.org", "10mail.tk", "10minutesmail.com",
  "20minutemail.com", "20minutemail.it", "30minutemail.com", "60minutemail.com",
  // guerrillamail
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org", "guerrillamail.biz",
  "guerrillamail.de", "guerrillamail.info", "guerrillamailblock.com", "grr.la",
  "sharklasers.com", "spam4.me", "pokemail.net",
  // mailinator family
  "mailinator.com", "mailinator.net", "mailinator.org", "mailinator2.com",
  "mailinator2.net", "notmailinator.com", "reallymymail.com", "sogetthis.com",
  "streetwisemail.com", "suremail.info", "thisisnotmyrealemail.com", "tradermail.info",
  "veryrealemail.com", "zippymail.info", "binkmail.com", "bobmail.info",
  "chammy.info", "devnullmail.com", "letthemeatspam.com", "mailin8r.com",
  "mailinater.com", "mailinator.us", "mailinator.info", "safetymail.info",
  "safetypost.de", "sendspamhere.com", "spamherelots.com", "spamhereplease.com",
  "spamthisplease.com", "tempinbox.com", "thisisnotmyrealemail.com",
  // tempmail family
  "tempmail.com", "tempmail.net", "tempmail.org", "tempmail.us", "tempmail.io",
  "tempmail.dev", "tempmail.email", "tempmail.plus", "tempmailaddress.com",
  "tempmailer.com", "tempmailer.de", "tempemail.co", "tempemail.com", "tempemail.net",
  "temp-mail.org", "temp-mail.io", "temp-mail.com", "temp-mail.ru", "tempinbox.com",
  "tempmailbox.net", "tmpmail.org", "tmpmail.net", "tmail.com", "tmail.ws",
  "tmail.io", "tmails.net", "throwawaymail.com", "throwam.com", "throwaway.email",
  // fakemail / yopmail
  "yopmail.com", "yopmail.net", "yopmail.fr", "cool.fr.nf", "jetable.fr.nf",
  "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr", "courriel.fr.nf",
  "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
  "fakemail.net", "fakemail.com", "fakeinbox.com", "fakeinbox.net", "fake-mail.ml",
  "fakemailz.com",
  // maildrop / getnada / etc
  "maildrop.cc", "getnada.com", "nada.email", "getairmail.com", "getairmail.net",
  "dropmail.me", "trashmail.com", "trashmail.de", "trashmail.io", "trashmail.net",
  "trashmail.ws", "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "wegwerfemail.de", "wegwerpmailadres.nl", "sneakmail.de", "spambox.us",
  "spambog.com", "spambog.de", "spambog.ru", "spamgourmet.com", "spamgourmet.net",
  "spamgourmet.org", "spamex.com", "spam.la", "spamavert.com", "spamfree24.org",
  "spamfree24.de", "spamfree24.eu", "spamfree24.info", "spamfree24.net",
  // mohmal / etc
  "mohmal.com", "mohmal.in", "mohmal.tech", "mailcatch.com", "mailnesia.com",
  "mailnull.com", "maileimer.de", "mailexpire.com", "mailfa.tk", "mailforspam.com",
  "mailfreeonline.com", "mailguard.me", "mailhazard.com", "mailmoat.com",
  "mailscrap.com", "mailtemp.info", "mailtothis.com", "mailzilla.com",
  "mailzilla.org", "mailzilla.orgmbx.cc",
  // burner / instant
  "burnermail.io", "burner-email.com", "burnerapp.com", "instantemailaddress.com",
  "instant-mail.de", "getonemail.com", "getonemail.net",
  // proton (not disposable but many temp orgs) — keeping out; only true disposable.
  // more
  "anonbox.net", "anonymbox.com", "armyspy.com", "cuvox.de", "dayrep.com",
  "einrot.com", "fleckens.hu", "gustr.com", "jourrapide.com", "rhyta.com",
  "superrito.com", "teleworm.us", "teleworm.com", "trbvm.com", "hidemail.de",
  "harakirimail.com", "incognitomail.com", "incognitomail.net", "incognitomail.org",
  "kasmail.com", "koszmail.pl", "letthemeatspam.com", "linshiyou.com",
  "mailtempo.online", "mailtemporary.com", "midlertidig-email.dk", "mintemail.com",
  "mytrashmail.com", "noclickemail.com", "nowmymail.com", "one-time.email",
  "onewaymail.com", "ourklips.com", "outlawspam.com", "put2.net", "putthisinyourspamdatabase.com",
  "quickmail.nl", "rcpt.at", "receiveee.com", "recyclemail.dk", "royal.net",
  "safe-mail.net", "selfdestructingmail.com", "sendspamhere.com", "shitmail.me",
  "sofimail.com", "sofort-mail.de", "solvemail.info", "sohu.com.tw",
  "spamavert.com", "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net",
  "spamcowboy.org", "spamday.com", "spamdecoy.net", "spamex.com", "spamfellas.com",
  "spamfree.eu", "spamherelots.com", "spamhole.com", "spamify.com", "spaminator.de",
  "spamkill.info", "spaml.com", "spammotel.com", "spamobox.com", "spamoff.de",
  "spamsalad.in", "spamslicer.com", "spamspot.com", "spamtroll.net", "speed.1s.fr",
  "supergreatmail.com", "supermailer.jp", "susi.mailexpire.com", "tafmail.com",
  "temporarily.de", "temporarioemail.com.br", "temporaryemail.net",
  "temporaryemail.us", "temporaryforwarding.com", "temporaryinbox.com",
  "thankyou2010.com", "trash2009.com", "trash-amil.com", "trashdevil.com",
  "trashemail.de", "trashmail.at", "trashymail.com", "tyldd.com", "uggsrock.com",
  "wetrainbayarea.com", "wetrainbayarea.org", "whyspam.me", "willselfdestruct.com",
  "winemaven.info", "wronghead.com", "wuzupmail.net", "xagloo.com", "yeah.net",
  "yuurok.com", "zoemail.net", "zoemail.org",
  // newer generation
  "mail-temporaire.fr", "mail-temporaire.com", "temporary-mail.net",
  "tempmail.altmails.com", "altmails.com", "1secmail.com", "1secmail.net",
  "1secmail.org", "esiix.com", "wwjmp.com", "xojxe.com", "yoggm.com",
  "fexpost.com", "mailhole.de", "moakt.com", "moakt.cc", "moakt.co",
  "tempr.email", "discard.email", "discardmail.com", "discardmail.de",
  "smaillite.com", "smailpro.com", "cs.email", "gemmedia.pl", "generator.email",
  "emlpro.com", "emltmp.com", "emlhub.com", "developermail.com",
  "internxt.com", "linshi-email.com", "mailpoof.com", "mailtm.com",
  "mail.tm", "mail.gw", "duck.com", "guerrillamail.com",
  // more common temp providers
  "byom.de", "chacuo.net", "027168.com", "0815.ru", "0clickemail.com",
  "0wnd.net", "0wnd.org", "1chuan.com", "2prong.com", "3d-painting.com",
  "5ymail.com", "9ox.net", "a-bc.net", "afrobacon.com", "ajaxapp.net",
  "amilegit.com", "amiri.net", "amiriindustries.com", "anonmails.de",
  "antichef.com", "antichef.net", "asdasd.ru", "azmeil.tf", "beefmilk.com",
  "big1.us", "bigstring.com", "bio-muesli.net", "boxformail.in", "brefmail.com",
  "bsnow.net", "bugmenot.com", "buymoreplays.com", "byebyemail.com",
  "cek.pm", "centermail.com", "centermail.net", "clixser.com", "cmail.com",
  "cmail.net", "cmail.org", "cool.fr.nf", "correo.blogos.net", "cosmorph.com",
  "courriel.fr.nf", "courrieltemporaire.com", "crapmail.org", "cust.in",
  "dacoolest.com", "dandikmail.com", "deadaddress.com", "deadspam.com",
  "delikkt.de", "despam.it", "devnullmail.com", "dfgh.net", "digitalsanctuary.com",
  "dingbone.com", "discard.email", "discardmail.com", "discardmail.de",
  "disposableaddress.com", "disposableemailaddresses.com", "disposableinbox.com",
  "disposeamail.com", "disposemail.com", "dispostable.com", "dodgeit.com",
  "dodgit.com", "dontreg.com", "dontsendmespam.de", "drdrb.net", "dump-email.info",
  "dumpandjunk.com", "dumpyemail.com", "e-mail.com", "e-mail.org", "e4ward.com",
  "email60.com", "emailgo.de", "emailias.com", "emailigo.de", "emailinfive.com",
  "emailmiser.com", "emailproxsy.com", "emailsensei.com", "emailtemporanea.com",
  "emailtemporanea.net", "emailtemporario.com.br", "emailthe.net", "emailtmp.com",
  "emailwarden.com", "emailx.at.hm", "emailxfer.com", "emeil.in", "emeil.ir",
  "emz.net", "evopo.com", "explodemail.com", "eyepaste.com", "fakedemail.com",
  "fakeinformation.com", "fansworldwide.de", "fastacura.com", "fastchevy.com",
  "fastchrysler.com", "fasteruna.com", "fastkawasaki.com", "fastmazda.com",
  "fastmitsubishi.com", "fastnissan.com", "fastsubaru.com", "fastsuzuki.com",
  "fasttoyota.com", "fastyamaha.com", "filzmail.com", "fizmail.com",
  "fleckens.hu", "frapmail.com", "friendlymail.co.uk", "fux0ringduh.com",
  "garliclife.com", "get2mail.fr", "getmails.eu", "ghosttexter.de", "girlsundertheinfluence.com",
  "gishpuppy.com", "goemailgo.com", "great-host.in", "greensloth.com",
  "gsrv.co.uk", "guerillamail.biz", "guerillamail.com", "guerillamail.info",
  "guerillamail.net", "guerillamail.org", "guerillamailblock.com",
  "haltospam.com", "hidzz.com", "hochsitze.com", "hotpop.com", "hulapla.de",
  "ieatspam.eu", "ieatspam.info", "ihateyoualot.info", "iheartspam.org",
  "imails.info", "inboxalias.com", "inboxclean.com", "inboxclean.org",
  "infocom.zp.ua", "instant-mail.de", "ipoo.org", "irish2me.com", "iwi.net",
  "jetable.com", "jetable.fr.nf", "jetable.net", "jetable.org", "jnxjn.com",
  "jsrsolutions.com", "junk1e.com", "kaspop.com", "keepmymail.com",
  "killmail.com", "killmail.net", "klassmaster.com", "klzlk.com",
  "kulturbetrieb.info", "kurzepost.de", "lawlita.com", "lifebyfood.com",
  "link2mail.net", "litedrop.com", "loadby.us", "login-email.com",
  "lookugly.com", "lopl.co.cc", "lortemail.dk", "lr78.com", "m21.cc",
  "mail-filter.com", "mail-temporaire.fr", "mail.by", "mail.mezimages.net",
  "mail2rss.org", "mail333.com", "mailbidon.com", "mailblocks.com",
  "mailbucket.org", "mailde.de", "mailde.info", "maildrop.cc", "maileater.com",
  "mailexpire.com", "mailfa.tk", "mailfreeonline.com", "mailguard.me",
  "mailin8r.com", "mailincubator.com", "mailismagic.com", "mailme.lv",
  "mailme24.com", "mailmetrash.com", "mailmoat.com", "mailms.com",
  "mailnesia.com", "mailnull.com", "mailonaut.com", "mailorc.com",
  "mailpick.biz", "mailrock.biz", "mailscrap.com", "mailshell.com",
  "mailsiphon.com", "mailslapping.com", "mailslite.com", "mailtemp.info",
  "mailtome.de", "mailtothis.com", "mailtrash.net", "mailtv.net", "mailtv.tv",
  "mailzilla.com", "makemetheking.com", "manybrain.com", "mbx.cc",
  "mega.zik.dj", "meinspamschutz.de", "meltmail.com", "messagebeamer.de",
  "mierdamail.com", "mintemail.com", "misterpinball.de", "moburl.com",
  "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf", "msa.minsmail.com",
  "mt2009.com", "mt2014.com", "mycard.net.ua", "mycleaninbox.net",
  "mymail-in.net", "mypacks.net", "mypartyclip.de", "myphantomemail.com",
  "mysamp.de", "mytempemail.com", "mytempmail.com", "mytrashmail.com",
  "nabuma.com", "neomailbox.com", "nepwk.com", "nervmich.net", "nervtmich.net",
  "netmails.com", "netmails.net", "netzidiot.de", "neverbox.com", "nice-4u.com",
  "no-spam.ws", "noblepioneer.com", "nomail.pw", "nomail.xl.cx", "nomail2me.com",
  "nomorespamemails.com", "nospam.ze.tc", "nospam4.us", "nospamfor.us",
  "nospamthanks.info", "notmailinator.com", "nowhere.org", "nowmymail.com",
  "nurfuerspam.de", "nus.edu.sg", "nwldx.com", "objectmail.com", "obobbo.com",
  "odaymail.com", "odnorazovoe.ru", "oneoffemail.com", "onewaymail.com",
  "onlatedotcom.info", "online.ms", "oopi.org", "ordinaryamerican.net",
  "otherinbox.com", "ovpn.to", "owlpic.com", "pancakemail.com", "pcusers.otherinbox.com",
  "pjjkp.com", "plexolan.de", "poczta.onet.pl", "politikerclub.de", "pooae.com",
  "pookmail.com", "privacy.net", "privatdemail.net", "proxymail.eu",
  "prtnx.com", "putthisinyourspamdatabase.com", "pwrby.com", "qq.com",
  "quickinbox.com", "rcpt.at", "reallymymail.com", "recode.me", "recursor.net",
  "regbypass.com", "regbypass.comsafe-mail.net", "rmqkr.net", "royal.net",
  "rppkn.com", "rtrtr.com", "s0ny.net", "safe-mail.net", "safersignup.de",
  "safetymail.info", "safetypost.de", "sandelf.de", "saynotospams.com",
  "schafmail.de", "schrott-email.de", "secretemail.de", "secure-mail.biz",
  "senseless-entertainment.com", "services391.com", "sharedmailbox.org",
  "sharklasers.com", "shieldedmail.com", "shiftmail.com", "shitmail.me",
  "shitware.nl", "shmeriously.com", "shortmail.net", "sibmail.com", "sinnlos-mail.de",
  "slapsfromlastnight.com", "slaskpost.se", "smashmail.de", "smellfear.com",
  "snakemail.com", "sneakemail.com", "sneakmail.de", "snkmail.com",
  "sofimail.com", "solvemail.info", "sogetthis.com", "soodonims.com",
  "spam4.me", "spamail.de", "spamarrest.com", "spambob.net", "spambob.org",
  "spambog.com", "spambog.de", "spambog.ru", "spambox.info", "spambox.irishspringrealty.com",
  "spamcannon.com", "spamcannon.net", "spamcon.org", "spamcorptastic.com",
  "spamcowboy.com", "spamday.com", "spamex.com", "spamfree.eu", "spamfree24.com",
  "spamfree24.de", "spamfree24.eu", "spamfree24.info", "spamfree24.net",
  "spamfree24.org", "spamgoes.in", "spamgourmet.com", "spamgourmet.net",
  "spamherelots.com", "spamhereplease.com", "spamhole.com", "spamify.com",
  "spaminator.de", "spamkill.info", "spaml.com", "spaml.de", "spammotel.com",
  "spamobox.com", "spamsalad.in", "spamspot.com", "spamstack.net", "spamthis.co.uk",
  "spamtroll.net", "speed.1s.fr", "stinkefinger.net", "stop-my-spam.com",
  "stuffmail.de", "supergreatmail.com", "supermailer.jp", "superstachel.de",
  "suremail.info", "svk.jp", "sweetxxx.de", "tafmail.com", "tagyourself.com",
  "talkinator.com", "teewars.org", "teleworm.us", "tempalias.com", "tempe-mail.com",
  "tempemail.biz", "tempemail.co.za", "tempemail.net", "tempimail.com",
  "tempmail.eu", "tempmaildemand.com", "tempmailer.com", "tempmailer.de",
  "tempomail.fr", "temporarily.de", "temporarioemail.com.br", "temporaryemail.net",
  "temporaryemail.us", "temporaryforwarding.com", "temporaryinbox.com",
  "temporarymailaddress.com", "tempthe.net", "thankyou2010.com", "thc.st",
  "thelimestones.com", "thisisnotmyrealemail.com", "thismail.net", "throwawayemailaddresses.com",
  "tilien.com", "tittbit.in", "tizi.com", "tmail.ws", "tmailinator.com",
  "toomail.biz", "topranklist.de", "tradermail.info", "trash-mail.at",
  "trash-mail.com", "trash-mail.de", "trash2009.com", "trashdevil.com",
  "trashemail.de", "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.ws", "trashymail.com",
  "trbvm.com", "trialmail.de", "trillianpro.com", "twinmail.de", "tyldd.com",
  "uggsrock.com", "umail.net", "upliftnow.com", "uplipht.com", "uroid.com",
  "us.af", "venompen.com", "veryrealemail.com", "vidchart.com", "viditag.com",
  "viralplays.com", "vpn.st", "vsimcard.com", "vubby.com", "wasteland.rfc822.org",
  "webemail.me", "weg-werf-email.de", "wegwerf-email-addressen.de", "wegwerf-emails.de",
  "wegwerfadresse.de", "wegwerfemail.com", "wegwerfemail.de", "wegwerfmail.de",
  "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org", "wh4f.org",
  "whyspam.me", "willhackforfood.biz", "willselfdestruct.com", "winemaven.info",
  "wronghead.com", "wuzup.net", "wuzupmail.net", "xagloo.com", "xemaps.com",
  "xents.com", "xmaily.com", "xoxy.net", "yep.it", "yogamaven.com",
  "yopmail.com", "yopmail.fr", "yopmail.net", "yourdomain.com", "ypmail.webarnak.fr.eu.org",
  "yuurok.com", "z1p.biz", "za.com", "zehnminuten.de", "zehnminutenmail.de",
  "zetmail.com", "zippymail.info", "zoaxe.com", "zoemail.com", "zoemail.net",
  "zoemail.org", "zomg.info", "zxcv.com", "zxcvbnm.com", "zzz.com",
]);

/** Returns true if the email's domain is a known disposable/temporary provider. */
export function isDisposableEmail(email: string): boolean {
  if (!email || typeof email !== "string") return false;
  const at = email.lastIndexOf("@");
  if (at < 0) return false;
  const domain = email.slice(at + 1).trim().toLowerCase();
  if (!domain) return false;
  if (DISPOSABLE_DOMAINS.has(domain)) return true;
  // Also block subdomains of listed disposable roots (e.g. "foo.mailinator.com")
  const parts = domain.split(".");
  for (let i = 1; i < parts.length - 1; i++) {
    const suffix = parts.slice(i).join(".");
    if (DISPOSABLE_DOMAINS.has(suffix)) return true;
  }
  return false;
}

export const DISPOSABLE_EMAIL_MESSAGE =
  "Temporary or disposable email addresses aren't allowed. Please use your work email.";
