/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoominfoLeadsRouteImport } from './routes/zoominfo-leads'
import { Route as StoreRouteImport } from './routes/store'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LinkedinSalesNavigatorLeadsRouteImport } from './routes/linkedin-sales-navigator-leads'
import { Route as ApolloLeadsExportRouteImport } from './routes/apollo-leads-export'
import { Route as IndexRouteImport } from './routes/index'

const ZoominfoLeadsRoute = ZoominfoLeadsRouteImport.update({
  id: '/zoominfo-leads',
  path: '/zoominfo-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinSalesNavigatorLeadsRoute =
  LinkedinSalesNavigatorLeadsRouteImport.update({
    id: '/linkedin-sales-navigator-leads',
    path: '/linkedin-sales-navigator-leads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApolloLeadsExportRoute = ApolloLeadsExportRouteImport.update({
  id: '/apollo-leads-export',
  path: '/apollo-leads-export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apollo-leads-export': typeof ApolloLeadsExportRoute
  '/linkedin-sales-navigator-leads': typeof LinkedinSalesNavigatorLeadsRoute
  '/pricing': typeof PricingRoute
  '/store': typeof StoreRoute
  '/zoominfo-leads': typeof ZoominfoLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apollo-leads-export': typeof ApolloLeadsExportRoute
  '/linkedin-sales-navigator-leads': typeof LinkedinSalesNavigatorLeadsRoute
  '/pricing': typeof PricingRoute
  '/store': typeof StoreRoute
  '/zoominfo-leads': typeof ZoominfoLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apollo-leads-export': typeof ApolloLeadsExportRoute
  '/linkedin-sales-navigator-leads': typeof LinkedinSalesNavigatorLeadsRoute
  '/pricing': typeof PricingRoute
  '/store': typeof StoreRoute
  '/zoominfo-leads': typeof ZoominfoLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apollo-leads-export'
    | '/linkedin-sales-navigator-leads'
    | '/pricing'
    | '/store'
    | '/zoominfo-leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apollo-leads-export'
    | '/linkedin-sales-navigator-leads'
    | '/pricing'
    | '/store'
    | '/zoominfo-leads'
  id:
    | '__root__'
    | '/'
    | '/apollo-leads-export'
    | '/linkedin-sales-navigator-leads'
    | '/pricing'
    | '/store'
    | '/zoominfo-leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApolloLeadsExportRoute: typeof ApolloLeadsExportRoute
  LinkedinSalesNavigatorLeadsRoute: typeof LinkedinSalesNavigatorLeadsRoute
  PricingRoute: typeof PricingRoute
  StoreRoute: typeof StoreRoute
  ZoominfoLeadsRoute: typeof ZoominfoLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoominfo-leads': {
      id: '/zoominfo-leads'
      path: '/zoominfo-leads'
      fullPath: '/zoominfo-leads'
      preLoaderRoute: typeof ZoominfoLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-sales-navigator-leads': {
      id: '/linkedin-sales-navigator-leads'
      path: '/linkedin-sales-navigator-leads'
      fullPath: '/linkedin-sales-navigator-leads'
      preLoaderRoute: typeof LinkedinSalesNavigatorLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apollo-leads-export': {
      id: '/apollo-leads-export'
      path: '/apollo-leads-export'
      fullPath: '/apollo-leads-export'
      preLoaderRoute: typeof ApolloLeadsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApolloLeadsExportRoute: ApolloLeadsExportRoute,
  LinkedinSalesNavigatorLeadsRoute: LinkedinSalesNavigatorLeadsRoute,
  PricingRoute: PricingRoute,
  StoreRoute: StoreRoute,
  ZoominfoLeadsRoute: ZoominfoLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
