/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoominfoLeadsRouteImport } from './routes/zoominfo-leads'
import { Route as WebsiteDesignRouteImport } from './routes/website-design'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShaderLabRouteImport } from './routes/shader-lab'
import { Route as SampleDataRouteImport } from './routes/sample-data'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ManualLeadResearchRouteImport } from './routes/manual-lead-research'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as LinkedinSalesNavigatorLeadsRouteImport } from './routes/linkedin-sales-navigator-leads'
import { Route as ImportPreviewRouteImport } from './routes/import-preview'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApolloLeadsExportRouteImport } from './routes/apollo-leads-export'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedInvoiceOrderIdRouteImport } from './routes/_authenticated/invoice.$orderId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ZoominfoLeadsRoute = ZoominfoLeadsRouteImport.update({
  id: '/zoominfo-leads',
  path: '/zoominfo-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDesignRoute = WebsiteDesignRouteImport.update({
  id: '/website-design',
  path: '/website-design',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShaderLabRoute = ShaderLabRouteImport.update({
  id: '/shader-lab',
  path: '/shader-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleDataRoute = SampleDataRouteImport.update({
  id: '/sample-data',
  path: '/sample-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualLeadResearchRoute = ManualLeadResearchRouteImport.update({
  id: '/manual-lead-research',
  path: '/manual-lead-research',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinSalesNavigatorLeadsRoute =
  LinkedinSalesNavigatorLeadsRouteImport.update({
    id: '/linkedin-sales-navigator-leads',
    path: '/linkedin-sales-navigator-leads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImportPreviewRoute = ImportPreviewRouteImport.update({
  id: '/import-preview',
  path: '/import-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApolloLeadsExportRoute = ApolloLeadsExportRouteImport.update({
  id: '/apollo-leads-export',
  path: '/apollo-leads-export',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvoiceOrderIdRoute =
  AuthenticatedInvoiceOrderIdRouteImport.update({
    id: '/invoice/$orderId',
    path: '/invoice/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/apollo-leads-export': typeof ApolloLeadsExportRoute
  '/contact': typeof ContactRoute
  '/import-preview': typeof ImportPreviewRoute
  '/linkedin-sales-navigator-leads': typeof LinkedinSalesNavigatorLeadsRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/manual-lead-research': typeof ManualLeadResearchRoute
  '/mcp': typeof McpRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sample-data': typeof SampleDataRoute
  '/shader-lab': typeof ShaderLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/website-design': typeof WebsiteDesignRoute
  '/zoominfo-leads': typeof ZoominfoLeadsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/invoice/$orderId': typeof AuthenticatedInvoiceOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/apollo-leads-export': typeof ApolloLeadsExportRoute
  '/contact': typeof ContactRoute
  '/import-preview': typeof ImportPreviewRoute
  '/linkedin-sales-navigator-leads': typeof LinkedinSalesNavigatorLeadsRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/manual-lead-research': typeof ManualLeadResearchRoute
  '/mcp': typeof McpRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sample-data': typeof SampleDataRoute
  '/shader-lab': typeof ShaderLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/website-design': typeof WebsiteDesignRoute
  '/zoominfo-leads': typeof ZoominfoLeadsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/invoice/$orderId': typeof AuthenticatedInvoiceOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/apollo-leads-export': typeof ApolloLeadsExportRoute
  '/contact': typeof ContactRoute
  '/import-preview': typeof ImportPreviewRoute
  '/linkedin-sales-navigator-leads': typeof LinkedinSalesNavigatorLeadsRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/manual-lead-research': typeof ManualLeadResearchRoute
  '/mcp': typeof McpRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sample-data': typeof SampleDataRoute
  '/shader-lab': typeof ShaderLabRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/website-design': typeof WebsiteDesignRoute
  '/zoominfo-leads': typeof ZoominfoLeadsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/invoice/$orderId': typeof AuthenticatedInvoiceOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/apollo-leads-export'
    | '/contact'
    | '/import-preview'
    | '/linkedin-sales-navigator-leads'
    | '/loading'
    | '/login'
    | '/manual-lead-research'
    | '/mcp'
    | '/payment-failed'
    | '/payment-success'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/sample-data'
    | '/shader-lab'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/track-order'
    | '/website-design'
    | '/zoominfo-leads'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/api/health'
    | '/blog/$slug'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/invoice/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/apollo-leads-export'
    | '/contact'
    | '/import-preview'
    | '/linkedin-sales-navigator-leads'
    | '/loading'
    | '/login'
    | '/manual-lead-research'
    | '/mcp'
    | '/payment-failed'
    | '/payment-success'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/sample-data'
    | '/shader-lab'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/track-order'
    | '/website-design'
    | '/zoominfo-leads'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/api/health'
    | '/blog/$slug'
    | '/blog'
    | '/.mcp/invoke-tool/$tool'
    | '/invoice/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/apollo-leads-export'
    | '/contact'
    | '/import-preview'
    | '/linkedin-sales-navigator-leads'
    | '/loading'
    | '/login'
    | '/manual-lead-research'
    | '/mcp'
    | '/payment-failed'
    | '/payment-success'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/sample-data'
    | '/shader-lab'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/track-order'
    | '/website-design'
    | '/zoominfo-leads'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/api/health'
    | '/blog/$slug'
    | '/blog/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/invoice/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApolloLeadsExportRoute: typeof ApolloLeadsExportRoute
  ContactRoute: typeof ContactRoute
  ImportPreviewRoute: typeof ImportPreviewRoute
  LinkedinSalesNavigatorLeadsRoute: typeof LinkedinSalesNavigatorLeadsRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  ManualLeadResearchRoute: typeof ManualLeadResearchRoute
  McpRoute: typeof McpRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SampleDataRoute: typeof SampleDataRoute
  ShaderLabRoute: typeof ShaderLabRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WebsiteDesignRoute: typeof WebsiteDesignRoute
  ZoominfoLeadsRoute: typeof ZoominfoLeadsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoominfo-leads': {
      id: '/zoominfo-leads'
      path: '/zoominfo-leads'
      fullPath: '/zoominfo-leads'
      preLoaderRoute: typeof ZoominfoLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-design': {
      id: '/website-design'
      path: '/website-design'
      fullPath: '/website-design'
      preLoaderRoute: typeof WebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shader-lab': {
      id: '/shader-lab'
      path: '/shader-lab'
      fullPath: '/shader-lab'
      preLoaderRoute: typeof ShaderLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-data': {
      id: '/sample-data'
      path: '/sample-data'
      fullPath: '/sample-data'
      preLoaderRoute: typeof SampleDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-lead-research': {
      id: '/manual-lead-research'
      path: '/manual-lead-research'
      fullPath: '/manual-lead-research'
      preLoaderRoute: typeof ManualLeadResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-sales-navigator-leads': {
      id: '/linkedin-sales-navigator-leads'
      path: '/linkedin-sales-navigator-leads'
      fullPath: '/linkedin-sales-navigator-leads'
      preLoaderRoute: typeof LinkedinSalesNavigatorLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-preview': {
      id: '/import-preview'
      path: '/import-preview'
      fullPath: '/import-preview'
      preLoaderRoute: typeof ImportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apollo-leads-export': {
      id: '/apollo-leads-export'
      path: '/apollo-leads-export'
      fullPath: '/apollo-leads-export'
      preLoaderRoute: typeof ApolloLeadsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invoice/$orderId': {
      id: '/_authenticated/invoice/$orderId'
      path: '/invoice/$orderId'
      fullPath: '/invoice/$orderId'
      preLoaderRoute: typeof AuthenticatedInvoiceOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoiceOrderIdRoute: typeof AuthenticatedInvoiceOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoiceOrderIdRoute: AuthenticatedInvoiceOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApolloLeadsExportRoute: ApolloLeadsExportRoute,
  ContactRoute: ContactRoute,
  ImportPreviewRoute: ImportPreviewRoute,
  LinkedinSalesNavigatorLeadsRoute: LinkedinSalesNavigatorLeadsRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  ManualLeadResearchRoute: ManualLeadResearchRoute,
  McpRoute: McpRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SampleDataRoute: SampleDataRoute,
  ShaderLabRoute: ShaderLabRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WebsiteDesignRoute: WebsiteDesignRoute,
  ZoominfoLeadsRoute: ZoominfoLeadsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiHealthRoute: ApiHealthRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
