DELETE FROM public.chatbot_kb;

INSERT INTO public.chatbot_kb (category, title, answer, sort_order) VALUES
('services', '📊 Lead generation (Apollo)', 'Verified B2B leads pulled from Apollo. Fixed pricing: 5,000 leads = $20 total; 10,000 leads = $35 total. Delivered as CSV within 24 hours. Fields include name, role, company, email, LinkedIn, website.', 10),
('services', '🏢 ZoomInfo enterprise data', 'Premium ZoomInfo lead lists with HQ phone numbers, direct dials and current job titles. Starts at $50 per targeted list. Best for enterprise ABM.', 20),
('services', '🔎 LinkedIn Sales Navigator export', 'Fresh Sales Navigator exports with current job titles, employer, industry and connection paths. Great for outbound ready-to-message lists.', 30),
('services', '✍️ Manual lead research', 'Fully manual research for niche ICPs — any data field you need (custom criteria). We source, verify and format to your spec. From $20 per list.', 40),
('services', '🌐 Website & app development', 'Custom-coded websites, AI-built websites, and full custom apps. Website design starts at $50 (logo) / $100 (AI-built) / $200 (custom). Timelines depend on scope.', 50),
('services', '📣 Google & Meta ads setup', 'Full setup for Google Ads and Meta (Facebook / Instagram) — pixel install, campaign build, audience targeting. From $100 per platform. We do NOT run TikTok or other platforms.', 60),
('services', '🎨 Logo & brand design', 'Custom logo design from $50. Includes 3 concepts, unlimited revisions on the picked direction, all source files.', 70),
('services', '📌 Facebook Pixel install', 'Server + client-side Facebook Pixel install with event tracking (Add-to-Cart, Purchase, Lead). $100 flat.', 80),

('catalog', 'SaaS Founders & Decision Makers — 5,000', '$79 (was $149). 5,000 verified SaaS founders & C-suite in USA/UK/Canada. Fields: name, role, company, email, LinkedIn, website, company size. → /store', 10),
('catalog', 'Shopify Plus Store Owners — 3,200', '$69 (was $129). 3,200 owners of $1M+ Shopify Plus stores, global. Fields: name, role, store URL, email, LinkedIn, est. revenue. → /store', 20),
('catalog', 'Fortune 1000 Executive List — 2,500', '$99 (was $199). 2,500 VP+ execs at Fortune 1000, USA. Includes direct-dial mobiles where available. → /store', 30),
('catalog', 'Series A Startup Founders NYC — 1,240', '$59. Founders at Series A NYC startups. → /store', 40),
('catalog', 'US Real Estate Agents (Top Producers) — 4,800', '$65. Top-producing US real estate agents. → /store', 50),
('catalog', 'US Healthcare Decision Makers — 1,900', '$89. Verified US healthcare decision makers. → /store', 60),
('catalog', 'European E-commerce CMOs — 1,650', '$75. European ecommerce CMOs & marketing leads. → /store', 70),
('catalog', 'B2B Agency Owners & Founders — 2,100', '$55. Agency owners and founders — great for B2B outreach. → /store', 80),
('catalog', 'VP Growth at Fintech Series B — 1,400', '$85. VPs of Growth at Series B fintechs. → /store', 90),

('pricing', 'Apollo — 5,000 leads', '$20 flat. Delivered as CSV within 24 hours.', 10),
('pricing', 'Apollo — 10,000 leads', '$35 flat. Delivered as CSV within 24 hours.', 20),
('pricing', 'ZoomInfo custom list', 'From $50. Includes HQ phone + direct dial where available.', 30),
('pricing', 'LinkedIn Sales Navigator export', 'From $20. Current titles, industry, connection paths.', 40),
('pricing', 'Manual research (any criteria)', 'From $20 per list. Priced by complexity & volume.', 50),
('pricing', 'Facebook Pixel install', '$100 flat.', 60),
('pricing', 'Google Ads setup', '$100 flat.', 70),
('pricing', 'Logo design', '$50 flat. 3 concepts, all source files.', 80),
('pricing', 'AI website design', '$100 flat.', 90),
('pricing', 'Custom-coded website', 'From $200. Depends on scope — request a quote.', 100),
('pricing', 'Volume discounts', 'Yes — bulk lead orders (25k+) get automatic discounts. Ask for a custom quote.', 110),

('faq', 'How fresh is the data?', 'All leads are verified within the last 30 days before delivery. Emails run through a validator; bounced rows are replaced free.', 10),
('faq', 'What formats do you deliver?', 'CSV by default. XLSX or Google Sheets on request — no extra charge.', 20),
('faq', 'Can I get a free sample?', 'Yes — every list ships with a free 10-row sample on request before payment. Tap "Talk to a human" to request one.', 30),
('faq', 'What countries do you cover?', 'Global coverage. Strongest in USA, Canada, UK, EU, Australia. Ask for a specific country and we will confirm volume.', 40),
('faq', 'What is your bounce guarantee?', 'Under 5% bounce rate guaranteed. If a delivery exceeds that, we replace bounced rows free within 7 days.', 50),
('faq', 'How long does delivery take?', 'Prebuilt lists: instant download after payment. Apollo custom lists: within 24 hours. Manual research: 2–5 business days.', 60),
('faq', 'Do you accept custom criteria?', 'Yes — job title, industry, revenue, headcount, tech stack, funding stage, location, seniority, and more. Tell us your ICP.', 70),
('faq', 'How do payments work?', 'We accept card (Stripe), PayPal, and crypto. Invoice on request for orders over $200.', 80),
('faq', 'Can I resell the data?', 'No — data is licensed for your own outbound only. Ask about reseller/enterprise licenses if needed.', 90),
('faq', 'Is the data GDPR / CCPA compliant?', 'Yes — sourced from publicly available business records. We include an opt-out header field in every delivery.', 100),

('policies', 'Refund policy', 'Full refund within 24 hours if we have not started delivery. After delivery, we replace bounced rows free but do not refund. Full policy → /refund-policy', 10),
('policies', 'Privacy policy', 'We only collect data needed to fulfill your order. We never share customer info. Full policy → /privacy-policy', 20),
('policies', 'Terms of service', 'Read the full terms → /terms', 30),

('pages', 'Browse the store', 'See all prebuilt lead products with prices, sample rows, and instant CSV download → /store', 10),
('pages', 'Full pricing page', 'All services with transparent pricing side-by-side → /pricing', 20),
('pages', 'Apollo leads export', 'Learn about our Apollo export service → /apollo-leads-export', 30),
('pages', 'ZoomInfo leads', 'Enterprise ZoomInfo data details → /zoominfo-leads', 40),
('pages', 'LinkedIn Sales Navigator leads', 'Sales Nav export details → /linkedin-sales-navigator-leads', 50),
('pages', 'Manual lead research', 'Fully custom research service → /manual-lead-research', 60),
('pages', 'Website design service', 'Custom + AI website builds → /website-design', 70),
('pages', 'Track your order', 'Enter your order ID for live status → /track-order', 80),
('pages', 'Free sample data', 'See what our deliveries look like → /sample-data', 90),
('pages', 'Contact us', 'Reach the team directly → /contact', 100),
('pages', 'Blog & guides', 'Deliverability, ICP scoring, data-source comparisons → /blog', 110),

('blog', 'Cold email deliverability playbook (2026)', 'Latest inbox-placement tactics: warmup, SPF/DKIM/DMARC, throttling, list hygiene. → /blog/cold-email-deliverability-2026', 10),
('blog', 'Apollo vs. ZoomInfo vs. LinkedIn (2026)', 'Head-to-head test on a 2,500-account US mid-market ICP — who wins on coverage, freshness and cost. → /blog/apollo-vs-zoominfo-vs-linkedin', 20),
('blog', '5-minute ICP scoring framework', 'A practical scoring rubric to focus outbound on your top-fit accounts. → /blog/icp-scoring-framework', 30),
('blog', 'CRM hygiene automations for SDR teams', 'Six automations to keep your CRM clean and compounding. → /blog/crm-hygiene-automations', 40),

('help', 'How order status works', 'Give us your order ID (e.g. ORD-1042) — the bot pulls the current status and any notes from our team.', 10),
('help', 'Hours', 'Sunday–Thursday, 9am–7pm (GMT+6). Outside hours: leave a ticket and we reply first thing next business day.', 20),
('help', 'Talk to a human', 'Tap "Talk to a human" and a team member joins the chat live via Telegram. Median first-response under 5 minutes during hours.', 30);